/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BusinessIdeasRouteImport } from './routes/business-ideas'
import { Route as IndexRouteImport } from './routes/index'

const BusinessIdeasRoute = BusinessIdeasRouteImport.update({
  id: '/business-ideas',
  path: '/business-ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business-ideas': typeof BusinessIdeasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business-ideas': typeof BusinessIdeasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business-ideas': typeof BusinessIdeasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/business-ideas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/business-ideas'
  id: '__root__' | '/' | '/business-ideas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessIdeasRoute: typeof BusinessIdeasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/business-ideas': {
      id: '/business-ideas'
      path: '/business-ideas'
      fullPath: '/business-ideas'
      preLoaderRoute: typeof BusinessIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessIdeasRoute: BusinessIdeasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
